---
name: CI
on: [pull_request]
env:
  CI: GH
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - 'pypy-3.7'
          - 'pypy-3.8'
      fail-fast: false
    name: Test on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
